### ISSUE TITLE
As a user I can only transfer tokens when I am whitelisted

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/contracts#14]
### Context
The FND token contract keeps track of the FND token balances on the ethereum accounts. Before the token sale only addresses that are whitelisted are allowed to transfer tokens and only to the FundRequest Platform Contract. The FundRequest Platform Contract can transfer tokens to any address.

### Additional information
The FND token contract must contain a parameter (allowAnyTransfer) that enables/disables the possibility to transfer tokens between any ethereum address:
- By default this parameter is set to false
- If the parameter is false ethereum addresses (expect the FundRequest Platform Contract)  can only transfer FND if they are whitelisted and they can only transfer to the Platform Contract address.
- The platform contract can transfer FND to any ethereum address.
- There is a function that allows to change this parameter that can only be called by a FundRequest account.
- When the parameter is set to true, all transfers of FND between any address are allowed.

A function is available to whitelist an ethereum address. This function can only be called by a FundRequest account.

### Testcases

- Testcase: A user transfers FND to the Platform contract, allowAnyTransfer=false, the user his address is not whitelisted.
   - Result: The FND are not transferred.
- Testcase: A user transfers FND to the Platform contract, allowAnyTransfer=false, the user his address is whitelisted.
   - Result: The FND are transferred.
- Testcase: A user transfers FND to another address as the Platform contract, allowAnyTransfer=false, the user his address is whitelisted.
   - Result: The FND are not transferred.
- Testcase: A user transfers FND to another address as the Platform contract, allowAnyTransfer=false, the user his address is not whitelisted.
   - Result: The FND are not transferred.
- Testcase: A user transfers FND to the Platform contract, allowAnyTransfer=true, the user his address is not whitelisted.
   - Result: The FND are transferred.
- Testcase: A user transfers FND to another address as the Platform contract, allowAnyTransfer=true, the user his address is not whitelisted.
   - Result: The FND are transferred.
 - Testcase: A user transfers FND to another address as the Platform contract, allowAnyTransfer=true, the user his address is not whitelisted.
   - Result: The FND are transferred.
 - Testcase: The Platform Contract transfers FND to another address as the Platform contract, allowAnyTransfer=false.
   - Result: The FND are transferred.
- Testcase: The Platform Contract transfers FND to another address as the Platform contract, allowAnyTransfer=true.
   - Result: The FND are transferred.

**Comment by Qkyrie** [comment]
this was merged into master
