### ISSUE TITLE
As a security auditor I log a major security breach in the FundRequest Smart Contracts #1

### ISSUE THREAD

**Issue by gerbert-vandenberghe** [FundRequest/contracts#41]
## Description
As FundRequest we want our community to audit the FundRequest contracts to make sure we get the best audit possible.

---
### Scope of Ticket
* Only FundRequest platform contracts: 
https://github.com/FundRequest/contracts/tree/master/contracts/platform

* Find a  **Major security breach**
```
A major security breach qualifies as an issue in the FundRequest production code base that can cause: 
- a loss of funds;
- a loss of control over the smart contracts;
- an outage of the production environment;
```
---

### Reward
The first reward is **$10 000** in FundRequest tokens (FND), for each subsequent major security issue the bounty is lowered by $1 000 in FundRequest tokens (FND).

---

### Precondition
* The auditor must be logged into <a href="https://fundrequest.io">fundrequest</a>
* The auditor must have experience in Solidity, Code Review & auditing

### Flow: Create Pull Request
* Create a new issue in this repository
* Edit
``https://github.com/FundRequest/contracts/blob/develop/vulnerabilities.md`` 
* Add your name as an auditor
* Describe the security breach using the example template
![Screen Shot 2018-05-14 at 13.30.35.png](https://images.zenhubusercontent.com/5aaa534a4b5806bc2bcaf622/85d5dcff-1df4-4b57-a53d-01c6bcba83c8)
* Create a pull request with a reference to the GitHub issue you created, this will be used by the FundRequest platform. (<a href="https://help.github.com/articles/closing-issues-using-keywords/">How to reference an issue in a GitHub Pull request?</a>)
* FundRequest administrator(s) will review the pull request and validate the reported issue

### Postcondition
* The auditor succesfully created a ticket and pull request
* The FundRequest team has successfully reviewed the pull request and funded the issue with $10,000 (or less) in FND tokens (<a href="https://www.cryptocompare.com/coins/fnd/overview/ETH">price of FND</a>)
* The FundRequest team merges the pull request
* The auditor can claim the funds once the platform is live (May 2018)
---

### Acceptance criteria
* The reported issue is considered a major security breach as stated in the ticket
* The security breach has to be unique. 
* The first person reporting the breach will be awarded the bounty. 
* The timestamp of the pull request will be used to define the first person who reported the security breach.
* The bug may only be reported in this the FundRequest Github repository and cannot be made public on other platforms/media without the consent of the FundRequest team.
* Determinations of eligibility, rewards and all terms related to an award are at the sole and final discretion of the FundRequest team.
* The issue is reported before June 2018

**Comment by gerbert-vandenberghe** [comment]
@davyvanroy @Qkyrie Please review.

**Comment by Sau0123** [comment]
Best project
