### ISSUE TITLE
Transaction fails when trying to refund certain issues

### ISSUE THREAD

**Issue by nico-ptrs** [FundRequest/contracts#57]
When trying to refund following issues, the transaction fails:
* https://tst1.fundrequest.io/requests/8 (https://kovan.etherscan.io/tx/0x09a3748dd05a841e73ea8decd3e2c7b0063f318e76a7ae73143bd0c7a921f7e8)
* https://tst1.fundrequest.io/requests/36 (https://kovan.etherscan.io/tx/0xd1e2e149dbd0d740ba5c0030e2dce2e98c07f68ae3d50e5bee8751670eed3c57)
* https://tst1.fundrequest.io/requests/17 (https://kovan.etherscan.io/tx/0x01f7b15a0ecb950d153eff3cfcb1ed58ffd2400d81ff1460ae5082527e5c94c2)

**Comment by Qkyrie** [comment]
Deployed
