### ISSUE TITLE
Assigning totalSupply to the owner

### ISSUE THREAD

**Issue by pauliax** [FundRequest/contracts#7]
### Expected behavior
During the Crowdsale it shouldn't be possible to transfer the ownership, otherwise, it could not go well.

### Actual behavior
  // Create initially all balance on the team multisig
    balances[owner] = totalSupply;

### Steps to reproduce the behavior
-

**Comment by Qkyrie** [comment]
We'll be using Minime tokens, so this ticket will be closed.
