### ISSUE TITLE
 "throw" is deprecated in favour of "revert()", "require()" and "assert()"

### ISSUE THREAD

**Issue by pauliax** [FundRequest/contracts#8]
### Expected behavior
    require(multisigWallet != address(0));

    require(startsAt <= endsAt);

  function() payable {
    revert();
  }

### Actual behavior
    if(multisigWallet == 0) {
        throw;
    }

    if(startsAt >= endsAt) {
        throw;
    }

  function() payable {
    throw;
  }

### Steps to reproduce the behavior
-

**Comment by Qkyrie** [comment]
Fortunately, this issue was already addressed in the develop branch. We're going to merge develop into master to make them more visible
